### ISSUE TITLE
Use locally downloaded Wiktionary data to generate Word Wise for epubs

### ISSUE THREAD

**Issue by woaidangyang** [xxyzz/WordDumb#43] opened 2022-07-17 04:29 UTC
### Describe the bug

Thank you so much for creating this great plugin!

I encountered the following error while trying to generate Word Wise for an epub file. I think it's because the access to the website hosting the Wiktionary data is blocked.

Since I can download the database manually via a browser routed with a proxy, is it possible to add an option asking the Worddumb plugin to use the database on my computer I downloaded?

### System Information

calibre, version 6.1.0 (win32, embedded-python: True)

### Error message

```text
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise for How to Lie with Statistics 
Job: "Generating Word Wise for How to Lie with Statistics" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 87, in do_job
  File "calibre_plugins.worddumb.parse_job", line 188, in dump_wiktionary_job
  File "calibre_plugins.worddumb.data.wiktionary", line 144, in download_and_dump_wiktionary
  File "calibre_plugins.worddumb.data.wiktionary", line 47, in extract_wiktionary
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 4954 (char 4953)
```

### Reproduce steps

Called with args: ((517, 'EPUB', 'C:\\Users\\Administrator\\Calibre Library\\Darrell Huff; Irving Geis\\How to Lie with Statistics (517)\\How to Lie with Statistics - Darrell Huff; Irving Geis.epub', <calibre.ebooks.metadata.book.base.Metadata object at 0x00000284096F0A30>, {'spacy': 'en_core_web_', 'wiki': 'en', 'kaikki': 'English'}), True, False) {'notifications': <queue.Queue object at 0x00000284096F0BB0>, 'abort': <threading.Event object at 0x00000284096F08E0>, 'log': <calibre.utils.logging.GUILog object at 0x00000284096F0C40>}

**Comment by xxyzz** [comment] 2022-07-17 04:39
You could move the Wiktionary json file to `~/AppData/Roaming/calibre/plugins/worddumb-lemmas/` for Windows, the plugin will detect the file.

Maybe the request is block because I didn't add the useragent header, I'll add it later.

**Comment by woaidangyang** [comment] 2022-07-17 04:54
Thank you so much for your quick reply! I'm trying it and let's see if it's working.

Not sure if this is the right place to ask. I also have some trouble to use the plugin to generate the X-Ray file. It says "Is GitHub/Wikipedia/Fandom blocked by your ISP? You might need tools to bypass internet censorship." Do you have any suggestions what kind of tools I can use to get the plugin bypass the Censorship?

**Comment by xxyzz** [comment] 2022-07-17 05:20
There are some free software mentioned in this page: https://en.wikipedia.org/wiki/Internet_censorship_circumvention

**Comment by woaidangyang** [comment] 2022-07-17 05:23
All right. The Word Wise for epubs is working!

But most of the words in the book are underscored now! lol

It would be great if only the words that pass a user defined difficulty level would be marked.

Great work, anyway!

**Comment by xxyzz** [comment] 2022-07-17 05:32
There is a "Customize EPUB Wiktionary" button in the plugin preferences dialog, you could enable or disable words at there.

**Comment by woaidangyang** [comment] 2022-07-17 05:34
I see. Got it. Thanks!

**Comment by woaidangyang** [comment] 2022-07-17 05:43
Sorry. It seems that the setting (Enabled: true/false) can't be saved. Also, there are too many word are marked "true" by default.

Maybe we can rank the words by their frequencies they would be met and the users can select which level of words we want the Worddumb to label?

**Comment by xxyzz** [comment] 2022-07-17 06:53
I forgot to save the Wiktionary JSON file... https://github.com/xxyzz/WordDumb/commit/55932f21c98d40a07fd8b7ef626522deedfd201e fixes this bug.

It kind hard to set difficult level for each word to fit most people's needs, so I expect the users to customize the table themselves.

**Comment by woaidangyang** [comment] 2022-07-17 07:00
OK. Thanks!

If I already have a list of words that I want the plugin to label, do you think there is an easy way to mark those words to "true" in a batch, instead of changing their status one by one?

**Comment by xxyzz** [comment] 2022-07-17 07:04
You could write some code to edit the Wiktionary JSON file stored in the `wordwise-lemmas` folder, the first data in each array is a bool value to enable or disable the word.

**Comment by woaidangyang** [comment] 2022-07-17 07:06
Cool! Thank you so much!

**Comment by xxyzz** [comment] 2022-07-17 08:14
User-agent header was added in https://github.com/xxyzz/WordDumb/commit/0d6559235a78468949721ee363a1706bd8848cd2. Hope it solves the download error.

**Comment by xxyzz** [comment] 2022-07-22 05:46
Hi @woaidangyang, you may want to test the new import from Anki .apkg or CSV file feature. Difficulty values are imported from Anki card type. The CSV file should has at least on column of the words and an optional difficulty column.

**Comment by woaidangyang** [comment] 2022-07-22 05:55
Super! This is the dream function I've been searching for a long time. It would be very useful for the language learners! Thank you so much!

**Comment by xxyzz** [comment] 2022-07-24 12:17
I didn't notice the download error was caused by Internet censorship since you said download through proxy works fine, so I'll close this issue now.

**Closed by xxyzz** 2022-07-24 12:17 UTC

**Comment by xxyzz** [comment] 2022-07-24 13:09
You may need to read the [calibre manual](https://manual.calibre-ebook.com/faq.html#how-do-i-get-calibre-to-use-my-http-proxy) and the [requests document](https://requests.readthedocs.io/en/latest/user/advanced/#proxies).
