### ISSUE TITLE
Can't generate X-ray and wordwise data

### ISSUE THREAD

**Issue by saad-bin-sohan** [xxyzz/WordDumb#181] opened 2024-01-17 08:01 UTC
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

tried again and again but same error keeps occurring

### Operating System name and version

macOS Sonoma 14.2.1

### Python version

3.12.1

### calibre version

7.3.

### WordDumb plugin version

3.30.0

### Error message

```text
calibre, version 7.3.0 (darwin, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Afterlives 
Job: "Generating Word Wise and X-Ray for Afterlives" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 202, in do_job
    run_subprocess(args, input_str)
  File "calibre_plugins.worddumb.utils", line 56, in run_subprocess
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/Users/sohan/Library/Preferences/calibre/plugins/WordDumb.zip', '{"book_id": 4, "book_path": "/Users/sohan/Calibre Library/Abdulrazak Gurnah/Afterlives (4)/Afterlives - Abdulrazak Gurnah.kfx", "mi": null, "book_fmt": "KFX", "book_lang": "en", "useragent": "WordDumb/3.30.0 (https://github.com/xxyzz/WordDumb)", "plugin_path": "/Users/sohan/Library/Preferences/calibre/plugins/WordDumb.zip", "spacy_model": "en_core_web_md", "create_ww": true, "create_x": true, "asin": "B09MH46CYZ", "acr": "CR!UQKXZVPKTPVEHW50O83YW9WCIAB1", "revision": "", "kfx_json": null, "mobi_html": null, "mobi_codec": ""}', '{"use_pos": true, "search_people": false, "model_size": "md", "zh_wiki_variant": "cn", "fandom": "", "add_locator_map": false, "preferred_formats": ["KFX", "AZW3", "AZW", "MOBI", "EPUB"], "use_all_formats": false, "minimal_x_ray_count": 1, "en_ipa": "ga_ipa", "zh_ipa": "pinyin", "choose_format_manually": true, "wiktionary_gloss_lang": "en", "kindle_gloss_lang": "en", "use_gpu": false, "cuda": "cu121", "last_opened_kindle_lemmas_language": "ca", "last_opened_wiktionary_lemmas_language": "ca", "use_wiktionary_for_kindle": false, "python_path": "", "ca_wiktionary_difficulty_limit": 5, "da_wiktionary_difficulty_limit": 5, "de_wiktionary_difficulty_limit": 5, "el_wiktionary_difficulty_limit": 5, "en_wiktionary_difficulty_limit": 5, "es_wiktionary_difficulty_limit": 5, "fi_wiktionary_difficulty_limit": 5, "fr_wiktionary_difficulty_limit": 5, "hr_wiktionary_difficulty_limit": 5, "it_wiktionary_difficulty_limit": 5, "ja_wiktionary_difficulty_limit": 5, "ko_wiktionary_difficulty_limit": 5, "lt_wiktionary_difficulty_limit": 5, "mk_wiktionary_difficulty_limit": 5, "nl_wiktionary_difficulty_limit": 5, "no_wiktionary_difficulty_limit": 5, "pl_wiktionary_difficulty_limit": 5, "pt_wiktionary_difficulty_limit": 5, "ro_wiktionary_difficulty_limit": 5, "ru_wiktionary_difficulty_limit": 5, "sl_wiktionary_difficulty_limit": 5, "sv_wiktionary_difficulty_limit": 5, "uk_wiktionary_difficulty_limit": 5, "zh_wiktionary_difficulty_limit": 5}']' returned non-zero exit status 1.
 
Called with args: (ParseJobData(book_id=4, book_path='/Users/sohan/Calibre Library/Abdulrazak Gurnah/Afterlives (4)/Afterlives - Abdulrazak Gurnah.kfx', mi=<calibre.ebooks.metadata.book.base.Metadata object at 0x134a312d0>, book_fmt='KFX', book_lang='en', useragent='WordDumb/3.30.0 (https://github.com/xxyzz/WordDumb)', plugin_path='/Users/sohan/Library/Preferences/calibre/plugins/WordDumb.zip', spacy_model='en_core_web_md', create_ww=True, create_x=True, asin='B09MH46CYZ', acr='CR!UQKXZVPKTPVEHW50O83YW9WCIAB1', revision='', kfx_json=None, mobi_html=None, mobi_codec=''),) {'notifications': <queue.Queue object at 0x134a332d0>, 'abort': <threading.Event at 0x134a322d0: unset>, 'log': <calibre.utils.logging.GUILog object at 0x134a32590>} 
Traceback (most recent call last):
  File "/Users/mymac/Library/Preferences/calibre/plugins/WordDumb.zip/dump_lemmas.py", line 5, in <module>
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/sohan/Library/Preferences/calibre/plugins/WordDumb.zip/__main__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/sohan/Library/Preferences/calibre/plugins/WordDumb.zip/dump_lemmas.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/sohan/Library/Preferences/calibre/plugins/WordDumb.zip/utils.py", line 51, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

### Plugin settings and reproduce steps

plugin settings are default

**Comment by xxyzz** [comment] 2024-01-17 08:36
Duplicate of #179

**Closed by xxyzz** 2024-01-17 08:36 UTC
