### ISSUE TITLE
Can't Generate WordWise/XRay

### ISSUE THREAD

**Issue by frizat82** [xxyzz/WordDumb#127] opened 2023-05-10 23:51 UTC
calibre, version 6.17.0 (linux, embedded-python: True)
Tonnerre de Brest!: An error occurred, please copy error message then report bug at GitHub.

Starting job: Generating Word Wise and X-Ray for Shop Class as Soulcraft: An Inquiry Into the Value of Work 
Job: "Generating Word Wise and X-Ray for Shop Class as Soulcraft: An Inquiry Into the Value of Work" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre_plugins.worddumb.parse_job", line 188, in do_job
    run_subprocess(args, input_str)
  File "calibre_plugins.worddumb.utils", line 51, in run_subprocess
    return subprocess.run(
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['python3', '/home/frizat/.config/calibre/plugins/WordDumb.zip', '{"create_ww": true, "create_x": true, "asin": "", "book_path": "/mnt/dataset/media/Books/Matthew B. Crawford/Shop Class as Soulcraft_ An Inquiry Into the Value of Work (10088)/Shop Class as Soulcraft_ An Inquiry Into t - Matthew B. Crawford.epub", "acr": "", "revision": "", "model": "en_core_web_md", "lemma_lang": "en", "mobi_codec": "", "useragent": "WordDumb/3.29.1 (https://github.com/xxyzz/WordDumb)", "book_fmt": "EPUB", "plugin_path": "/home/frizat/.config/calibre/plugins/WordDumb.zip"}', '{"use_pos": true, "search_people": true, "model_size": "md", "zh_wiki_variant": "cn", "fandom": "", "add_locator_map": false, "preferred_formats": ["KFX", "AZW3", "AZW", "MOBI", "EPUB"], "use_all_formats": false, "minimal_x_ray_count": 1, "en_ipa": "ga_ipa", "zh_ipa": "pinyin", "choose_format_manually": true, "wiktionary_gloss_lang": "en", "kindle_gloss_lang": "en", "use_gpu": false, "cuda": "cu118", "last_opened_kindle_lemmas_language": "ca", "last_opened_wiktionary_lemmas_language": "ca", "use_wiktionary_for_kindle": false, "ca_wiktionary_difficulty_limit": 5, "da_wiktionary_difficulty_limit": 5, "de_wiktionary_difficulty_limit": 5, "el_wiktionary_difficulty_limit": 5, "en_wiktionary_difficulty_limit": 5, "es_wiktionary_difficulty_limit": 5, "fi_wiktionary_difficulty_limit": 5, "fr_wiktionary_difficulty_limit": 5, "hr_wiktionary_difficulty_limit": 5, "it_wiktionary_difficulty_limit": 5, "ja_wiktionary_difficulty_limit": 5, "ko_wiktionary_difficulty_limit": 5, "lt_wiktionary_difficulty_limit": 5, "mk_wiktionary_difficulty_limit": 5, "nl_wiktionary_difficulty_limit": 5, "no_wiktionary_difficulty_limit": 5, "pl_wiktionary_difficulty_limit": 5, "pt_wiktionary_difficulty_limit": 5, "ro_wiktionary_difficulty_limit": 5, "ru_wiktionary_difficulty_limit": 5, "sv_wiktionary_difficulty_limit": 5, "uk_wiktionary_difficulty_limit": 5, "zh_wiktionary_difficulty_limit": 5}']' returned non-zero exit status 1.
 
Called with args: ((10088, 'EPUB', '/mnt/dataset/media/Books/Matthew B. Crawford/Shop Class as Soulcraft_ An Inquiry Into the Value of Work (10088)/Shop Class as Soulcraft_ An Inquiry Into t - Matthew B. Crawford.epub', <calibre.ebooks.metadata.book.base.Metadata object at 0x7f0dbe247f10>, 'en'), True, True) {'notifications': <queue.Queue object at 0x7f0dbe247610>, 'abort': <threading.Event object at 0x7f0dbe247550>, 'log': <calibre.utils.logging.GUILog object at 0x7f0dbe2473d0>} 
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frizat/.config/calibre/plugins/WordDumb.zip/__main__.py", line 40, in <module>
  File "/home/frizat/.config/calibre/plugins/WordDumb.zip/parse_job.py", line 312, in create_files
  File "/home/frizat/.config/calibre/plugins/WordDumb.zip/epub.py", line 232, in modify_epub
  File "/home/frizat/.config/calibre/plugins/WordDumb.zip/mediawiki.py", line 480, in query_mediawiki
  File "/home/frizat/.config/calibre/plugins/WordDumb.zip/mediawiki.py", line 140, in query
  File "/home/frizat/.config/calibre/plugins/WordDumb.zip/mediawiki.py", line 69, in add_cache
sqlite3.OperationalError: near "RETURNING": syntax error

**Comment by xxyzz** [comment] 2023-05-11 00:06
Duplicate of https://github.com/xxyzz/WordDumb/issues/115, Please update your Python/SQLite package.

**Closed by xxyzz** 2023-05-11 00:06 UTC
